# Generated by Django 4.0.4 on 2022-06-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_profile_avatar_alter_profile_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='cover_images'),
        ),
    ]
